export const list = [
  { id: 1, name: "Timer" },
  { id: 2, name: "Progress bar" },
  { id: 3, name: "Max count" },
  { id: 4, name: "Scroll to top" },
  { id: 5, name: "Change order" },
  { id: 6, name: "Sudoku" },
  //{ id: 7, name: "" },
];

export const RandomData = [
  {
    id: 1,
    first_name: "Simeon",
    last_name: "Calow",
    email: "scalow0@dyndns.org",
  },
  {
    id: 2,
    first_name: "Nehemiah",
    last_name: "Claydon",
    email: "nclaydon1@whitehouse.gov",
  },
  {
    id: 3,
    first_name: "Perri",
    last_name: "Cotelard",
    email: "pcotelard2@xinhuanet.com",
  },
  {
    id: 4,
    first_name: "Ariana",
    last_name: "Totaro",
    email: "atotaro3@constantcontact.com",
  },
  {
    id: 5,
    first_name: "Trescha",
    last_name: "Sowerby",
    email: "tsowerby4@java.com",
  },
  {
    id: 6,
    first_name: "Belita",
    last_name: "Dibben",
    email: "bdibben5@gizmodo.com",
  },
  {
    id: 7,
    first_name: "Susi",
    last_name: "McCluin",
    email: "smccluin6@ibm.com",
  },
  {
    id: 8,
    first_name: "Sheela",
    last_name: "Dallewater",
    email: "sdallewater7@eventbrite.com",
  },
  {
    id: 9,
    first_name: "Carmelina",
    last_name: "Daniells",
    email: "cdaniells8@adobe.com",
  },
  {
    id: 10,
    first_name: "Tannie",
    last_name: "Birtchnell",
    email: "tbirtchnell9@jalbum.net",
  },
  { id: 11, first_name: "Addie", last_name: "Fish", email: "afisha@github.io" },
  {
    id: 12,
    first_name: "Elinor",
    last_name: "Jeffcoat",
    email: "ejeffcoatb@cpanel.net",
  },
  {
    id: 13,
    first_name: "Perla",
    last_name: "Plain",
    email: "pplainc@skyrock.com",
  },
  {
    id: 14,
    first_name: "Tarra",
    last_name: "Dahlberg",
    email: "tdahlbergd@nytimes.com",
  },
  {
    id: 15,
    first_name: "Timmy",
    last_name: "Janeczek",
    email: "tjaneczeke@oaic.gov.au",
  },
  {
    id: 16,
    first_name: "Betteann",
    last_name: "Waliszek",
    email: "bwaliszekf@cyberchimps.com",
  },
  {
    id: 17,
    first_name: "Kimberli",
    last_name: "Kalker",
    email: "kkalkerg@miibeian.gov.cn",
  },
  {
    id: 18,
    first_name: "Gerick",
    last_name: "Lauthian",
    email: "glauthianh@msn.com",
  },
  {
    id: 19,
    first_name: "Jerrine",
    last_name: "Orrill",
    email: "jorrilli@dailymotion.com",
  },
  {
    id: 20,
    first_name: "Gibby",
    last_name: "Boyton",
    email: "gboytonj@squidoo.com",
  },
  {
    id: 21,
    first_name: "Belia",
    last_name: "Josselsohn",
    email: "bjosselsohnk@google.com.br",
  },
  {
    id: 22,
    first_name: "Brigitta",
    last_name: "de Mullett",
    email: "bdemullettl@domainmarket.com",
  },
  {
    id: 23,
    first_name: "Dougy",
    last_name: "Connar",
    email: "dconnarm@google.co.jp",
  },
  {
    id: 24,
    first_name: "Halsy",
    last_name: "Staniforth",
    email: "hstaniforthn@ameblo.jp",
  },
  {
    id: 25,
    first_name: "Tiffanie",
    last_name: "Bennet",
    email: "tbenneto@ca.gov",
  },
  {
    id: 26,
    first_name: "Barbra",
    last_name: "Munnion",
    email: "bmunnionp@phoca.cz",
  },
  {
    id: 27,
    first_name: "Reine",
    last_name: "Knights",
    email: "rknightsq@epa.gov",
  },
  {
    id: 28,
    first_name: "Marline",
    last_name: "Duiguid",
    email: "mduiguidr@bbb.org",
  },
  {
    id: 29,
    first_name: "Norry",
    last_name: "Lindsley",
    email: "nlindsleys@goo.gl",
  },
  {
    id: 30,
    first_name: "Hanni",
    last_name: "Farrens",
    email: "hfarrenst@auda.org.au",
  },
  {
    id: 31,
    first_name: "Timothee",
    last_name: "Cantillon",
    email: "tcantillonu@domainmarket.com",
  },
  {
    id: 32,
    first_name: "Christoph",
    last_name: "Dumphy",
    email: "cdumphyv@canalblog.com",
  },
  {
    id: 33,
    first_name: "Marin",
    last_name: "Pinare",
    email: "mpinarew@aboutads.info",
  },
  {
    id: 34,
    first_name: "Guillaume",
    last_name: "Sollime",
    email: "gsollimex@timesonline.co.uk",
  },
  {
    id: 35,
    first_name: "Terencio",
    last_name: "Gopsill",
    email: "tgopsilly@ask.com",
  },
  {
    id: 36,
    first_name: "Griffy",
    last_name: "Plom",
    email: "gplomz@amazonaws.com",
  },
  {
    id: 37,
    first_name: "Winnah",
    last_name: "Tourot",
    email: "wtourot10@bandcamp.com",
  },
  {
    id: 38,
    first_name: "Lazar",
    last_name: "Pavlovic",
    email: "lpavlovic11@buzzfeed.com",
  },
  {
    id: 39,
    first_name: "Clemmie",
    last_name: "Ewebank",
    email: "cewebank12@ustream.tv",
  },
  {
    id: 40,
    first_name: "Benedetto",
    last_name: "Willgress",
    email: "bwillgress13@ustream.tv",
  },
  {
    id: 41,
    first_name: "Carlie",
    last_name: "Van Halle",
    email: "cvanhalle14@hostgator.com",
  },
  {
    id: 42,
    first_name: "Tabbitha",
    last_name: "Soldi",
    email: "tsoldi15@4shared.com",
  },
  {
    id: 43,
    first_name: "Tucky",
    last_name: "Arcase",
    email: "tarcase16@mapy.cz",
  },
  {
    id: 44,
    first_name: "Vinson",
    last_name: "Bonafacino",
    email: "vbonafacino17@skyrock.com",
  },
  {
    id: 45,
    first_name: "Marius",
    last_name: "Angerstein",
    email: "mangerstein18@squidoo.com",
  },
  {
    id: 46,
    first_name: "Sylvester",
    last_name: "Poxson",
    email: "spoxson19@oakley.com",
  },
  {
    id: 47,
    first_name: "Bess",
    last_name: "Hawkswood",
    email: "bhawkswood1a@freewebs.com",
  },
  {
    id: 48,
    first_name: "Serge",
    last_name: "Bessey",
    email: "sbessey1b@dropbox.com",
  },
  {
    id: 49,
    first_name: "Gabriellia",
    last_name: "Barclay",
    email: "gbarclay1c@bing.com",
  },
  {
    id: 50,
    first_name: "Oralle",
    last_name: "Salamon",
    email: "osalamon1d@canalblog.com",
  },
];
